package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Type1 type1

swagger:model Type1
*/
type Type1 struct {

	/* characters
	 */
	Characters string `json:"characters,omitempty"`
}

func (m *Type1) Type() string {
	return "Type1"
}
func (m *Type1) SetType(val string) {

}

// UnmarshalJSON unmarshals this polymorphic type from a JSON structure
func (m *Type1) UnmarshalJSON(raw []byte) error {
	var data struct {
		Type string `json:"type,omitempty"`

		/* characters
		 */
		Characters string `json:"characters,omitempty"`
	}

	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	m.Characters = data.Characters

	return nil
}

// MarshalJSON marshals this polymorphic type to a JSON structure
func (m Type1) MarshalJSON() ([]byte, error) {
	var data struct {
		Type string `json:"type,omitempty"`

		/* characters
		 */
		Characters string `json:"characters,omitempty"`
	}

	data.Characters = m.Characters
	data.Type = "Type1"
	return json.Marshal(data)
}

// Validate validates this type1
func (m *Type1) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
