package models

import (
	"encoding/json"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Type2 type2

swagger:model Type2
*/
type Type2 struct {

	/* length
	 */
	Length *int64 `json:"length,omitempty"`
}

func (m *Type2) Type() string {
	return "Type2"
}
func (m *Type2) SetType(val string) {

}

// UnmarshalJSON unmarshals this polymorphic type from a JSON structure
func (m *Type2) UnmarshalJSON(raw []byte) error {
	var data struct {
		Type string `json:"type,omitempty"`

		/* length
		 */
		Length *int64 `json:"length,omitempty"`
	}

	if err := json.Unmarshal(raw, &data); err != nil {
		return err
	}

	m.Length = data.Length

	return nil
}

// MarshalJSON marshals this polymorphic type to a JSON structure
func (m Type2) MarshalJSON() ([]byte, error) {
	var data struct {
		Type string `json:"type,omitempty"`

		/* length
		 */
		Length *int64 `json:"length,omitempty"`
	}

	data.Length = m.Length
	data.Type = "Type2"
	return json.Marshal(data)
}

// Validate validates this type2
func (m *Type2) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
