package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*ParameterDefinition parameter definition

swagger:model ParameterDefinition
*/
type ParameterDefinition struct {

	/* generator
	 */
	Generator *ParameterGenerator `json:"generator,omitempty"`

	/* Parameter name

	Required: true
	*/
	Name string `json:"name"`
}

// Validate validates this parameter definition
func (m *ParameterDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ParameterDefinition) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}
